- name: MyEnv | setup_openstack | setup_kolla_ansible
  hosts: deploy
  roles:
    - setup_kolla_ansible

- name: MyEnv | setup_openstack | setup_kolla_build
  hosts: build
  roles:
    - setup_kolla_build

- name: MyEnv | setup_openstack | setup_node
  hosts: "openstack{{ project_name | d('') }}"
  roles:
    - setup_node
