- name: MyEnv | setup_openstack | setup_libvirt
  tags: libvirt
  hosts: localhost
  roles:
    - setup_libvirt

- name: MyEnv | setup_openstack | wait for target connection to become reachable/usable
  vars:
    openstack: "openstack{{'-' + project_name if project_name | d('') != '' else 'home'}}"
  hosts: deploy:build:{{ openstack }}
  gather_facts: no
  tasks:
    - wait_for_connection:
        delay: 5
        timeout: 15

- name: MyEnv | setup_openstack | setup_kolla_ansible
  tags: [deploy, openstack]
  hosts: deploy
  roles:
    - setup_kolla_ansible

- name: MyEnv | setup_openstack | setup_kolla_build
  tags: [build, openstack]
  hosts: build
  roles:
    - setup_docker
    - setup_kolla_build

- name: MyEnv | setup_openstack | setup_node
  tags: [node, openstack]
  hosts: "openstack{{ '-' + project_name if project_name | d('') != '' else '' }}"
  roles:
    - setup_node
