- name: setup_libvirt [debian] | install requirements
  package: name="{{ item }}"
  become: yes
  with_items: "{{ libvirt_requirements_debian }}"
  when: ansible_os_family == "Debian"

# For performance and security reasons, disable netfilter for bridges.
# See <https://bugzilla.redhat.com/show_bug.cgi?id=512206#c0>
- name: setup_libvirt [debian] | disable netfilter for bridges
  sysctl: name="{{ item }}" value=0
  become: yes
  with_items:
    - "net.bridge.bridge-nf-call-ip6tables"
    - "net.bridge.bridge-nf-call-iptables"
    - "net.bridge.bridge-nf-call-arptables"
  when: ansible_os_family == "Debian"

- name: setup_libvirt | create /var/lib/libvirt/images/* directories
  file:
    path: "/var/lib/libvirt/images/{{ item.name }}"
    mode: "644"
    state: directory
    recurse: yes
  become: yes
  with_items: "{{ libvirt_images }}"

- name: setup_libvirt | configure /var/lib/libvirt/images/*/*
  template:
    src: "{{ item[1] }}.j2"
    dest: "/var/lib/libvirt/images/{{item[0].name}}/{{ item[1] }}"
    mode: "664"
  become: yes
  with_nested:
    - "{{ libvirt_images }}"
    - [ "meta-data", "user-data" ]

- name: setup_libvirt | download system image from S3
  amazon.aws.aws_s3:
    bucket: "{{ bucket }}"
    object: "{{ item.image_src }}"
    s3_url: "{{ s3_url }}"
    region: "{{ region }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    dest: "{{ item.image_dst }}"
    mode: get
    overwrite: never
  ignore_errors: yes
  become: yes
  with_items: "{{ libvirt_images }}"
