kolla_openstack_release: "{{ openstack_release | d('victoria') }}"

kolla_options:
  victoria:
    openstack_tag: "victoria"
    tarballs_base: "https://tarballs.opendev.org"
    base_tag:
      debian: "stable-20210408"
      ubuntu: "20.04"
  train:
    openstack_tag: "9.3.2"
    tarballs_base: "https://tarballs.openstack.org"
    base_tag:
      ubuntu: "18.04"

# Possible values:
# - binary
# - source
kolla_install_type: source

# Possible values:
# - centos
# - debian
# - ubuntu
# - rhel
kolla_base_distro: ubuntu

kolla_docker_registry: "192.168.0.70:4000"
kolla_docker_namespace: kolla

kolla_network_interface: macvlan0
kolla_neutron_external_interface: macvtap0

kolla_internal_vip_address: "192.168.0.10"
kolla_external_vip_address: "192.168.0.11"
