libvirt_images:
  - name: kolla-ansible
    hostname: deploy
    users:
      - name: "{{ ansible_env.USER }}"
        public_key: "{{ ansible_env.HOME }}/.ssh/id_rsa.pub"
        groups:
          - sudo

    image_src: "cloud-images.ubuntu.com/focal/20210720/focal-server-cloudimg-amd64.img"
    image_dst: "/var/lib/libvirt/images/focal-server-cloudimg-amd64.img"


aws_access_key_path: "{{ ansible_env.HOME }}/.aws/aws_access_key"
aws_secret_key_path: "{{ ansible_env.HOME }}/.aws/aws_secret_key"
access_key: "{{ lookup('file', aws_access_key_path) }}"
secret_key: "{{ lookup('file', aws_secret_key_path) }}"
bucket: "bf084dfb-eeb9-4b82-9a43-9e1b77e6fa10"
s3_url: "https://storage.yandexcloud.net"
region: "ru-central1"
